title: "Buttons, buttons-oh my!"
description: |
  The buttons use our primary colour to draw attention and stand out. Each button has a specific purpose:
patterns:
  basic:
    title: "Basic"
    description: |
      This button should be used in almost all situations.
    fields:
      - name: "url"
      type: string
